title: Evening Mist
email: eveningmisthazel@gmail.com

description: > # this means to ignore newlines until "baseurl:"
 This is Evening Mist a Blog written By UNknow

baseurl: "https://eveningmist.github.io/eveningmist/"
url: "eveningmist.github.io/eveningmist/"

twitter_username: UNknow
github_username:  UNknow
facebook_username: UNknow

# Build settings
markdown: redcarpet

permalinks: /:day/:month/:year/:title/